// generated by sketch2assets
// from Sample.sketch
// to Sketch.xcassets

import UIKit
struct Sketch {
	static let Oval: UIImage = UIImage(named: "Oval") ?? UIImage()
	static let Polygon: UIImage = UIImage(named: "Polygon") ?? UIImage()
	static let Star: UIImage = UIImage(named: "Star") ?? UIImage()
}
