// generated by sketch2assets
// from Sample.sketch
// to Sketch.xcassets

import UIKit

struct Sketch {
	static var Oval: UIImage { return UIImage(named: "Oval") ?? UIImage() }
	static var Polygon: UIImage { return UIImage(named: "Polygon") ?? UIImage() }
	static var Star: UIImage { return UIImage(named: "Star") ?? UIImage() }
}
